### ISSUE TITLE
mlflow autolog saves torchmetrics' differentiable as False

### ISSUE THREAD

**Issue by marquis08** [Lightning-AI/torchmetrics#2077] opened 2023-09-12 07:23 UTC
## 🐛 Bug

It's literally the same as the title. I'm using mlflow with pytorch lightning and torchmetrics. And, I found that mlflow's autolog method saved 'differentiable'. I assume this parameter came from torchmetrics.

<img width="319" alt="image" src="https://github.com/Lightning-AI/torchmetrics/assets/27425140/9d503bca-181b-4da2-b5bc-253053420f1e">

### To Reproduce

The example code is integrated with mlflow.(example code comes from official documents in torchmetrics)

<details>
  <summary>Code sample</summary>

```python
import os
import mlflow
from torch import optim, nn, utils, Tensor
from torchvision.datasets import MNIST
from torchvision.transforms import ToTensor
import pytorch_lightning as pl

from torchmetrics import MeanSquaredError

# define any number of nn.Modules (or use your current ones)
encoder = nn.Sequential(nn.Linear(28 * 28, 64), nn.ReLU(), nn.Linear(64, 3))
decoder = nn.Sequential(nn.Linear(3, 64), nn.ReLU(), nn.Linear(64, 28 * 28))

# define the LightningModule
class LitAutoEncoder(pl.LightningModule):
    def __init__(self, encoder, decoder):
        super().__init__()
        self.encoder = encoder
        self.decoder = decoder
        self.criterion = MeanSquaredError()

    def training_step(self, batch, batch_idx):
        # training_step defines the train loop.
        # it is independent of forward
        x, y = batch
        x = x.view(x.size(0), -1)
        z = self.encoder(x)
        x_hat = self.decoder(z)
        loss = self.criterion(x_hat, x)
        # Logging to TensorBoard (if installed) by default
        self.log("train_loss", loss)
        return loss

    def configure_optimizers(self):
        optimizer = optim.Adam(self.parameters(), lr=1e-3)
        return optimizer

# init the autoencoder
autoencoder = LitAutoEncoder(encoder, decoder)

# setup data
dataset = MNIST(os.getcwd(), download=True, transform=ToTensor())
train_loader = utils.data.DataLoader(dataset)

# train the model (hint: here are some helpful Trainer arguments for rapid idea iteration)
trainer = pl.Trainer(limit_train_batches=100,
                    max_epochs=1)

mlflow.set_tracking_uri('http://0.0.0.0:5000')  # set up connection
mlflow.set_experiment('TorchMetrics_dummy')          # set the experiment comes from args.Title
mlflow.pytorch.autolog(log_models=False)
with mlflow.start_run(run_name="test", nested=False) as run:
    trainer.fit(model=autoencoder, train_dataloaders=train_loader)
```

</details>

### Expected behavior

I assume that mlflow should store `differentiable` parameter as `True` since default value of `torchmetrics.MeanSquaredError` is `is_differentiable = True`.  
However, it saved as `False`.

### Environment

- torchmetrics==0.11.4
- python==3.10.0
- torch==2.0.0
- pytorch-lightning==1.9.4
- mlflow==2.3.1

**Comment by SkafteNicki** [comment] 2023-09-12 07:48
Hi @marquis08, thanks for raising this issue.
After running your provided example, I could reproduce the results. Looking at the source code of `torch.optim.Adam` we can see that all the logged parameters in mlflow are actually parameters of the optimizer. In particular, it has a parameter `differentiable` that is `False` by default:
https://github.com/pytorch/pytorch/blob/main/torch/optim/adam.py#L14-L27
The problem is therefore unrelated to torchmetrics, and in general it seems to work as intended.
Closing issue.

**Closed by SkafteNicki** 2023-09-12 07:48 UTC
Labels: bug / fix, help wanted, v0.11.x
