### ISSUE TITLE
"RuntimeError 'bincount' with precision='16-mixed' on GPU with TorchMetrics 1.0.1"

### ISSUE THREAD

**Issue by mnslarcher** [Lightning-AI/torchmetrics#1946] opened 2023-07-28 07:57 UTC
## 🐛 Bug

When I run my script on a GPU using precision="16-mixed", I encounter the following error:
`RuntimeError: bincount only supports 1-d non-negative integral inputs.`

```
File "/opt/conda/lib/python3.10/site-packages/lightning_segmentation/lit_models/utils.py", line 26, in compute_metric
    metric(input, target)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torchmetrics/metric.py", line 290, in forward
    self._forward_cache = self._forward_reduce_state_update(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torchmetrics/metric.py", line 357, in _forward_reduce_state_update
    self.update(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torchmetrics/metric.py", line 456, in wrapped_func
    raise err
  File "/opt/conda/lib/python3.10/site-packages/torchmetrics/metric.py", line 446, in wrapped_func
    update(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torchmetrics/classification/confusion_matrix.py", line 250, in update
    confmat = _multiclass_confusion_matrix_update(preds, target, self.num_classes)
  File "/opt/conda/lib/python3.10/site-packages/torchmetrics/functional/classification/confusion_matrix.py", line 327, in _multiclass_confusion_matrix_update
    bins = _bincount(unique_mapping, minlength=num_classes**2)
  File "/opt/conda/lib/python3.10/site-packages/torchmetrics/utilities/data.py", line 241, in _bincount
    return torch.bincount(x, minlength=minlength)
```

Interestingly, when I run the same script on the CPU or if I disable mixed precision, everything works fine, even on the GPU. I'm uncertain if this is a "bug." Would a potential solution be explicitly converting the input and target to a specific format before passing them to the metric(input, target) function? Do you have any suggestions?

### To Reproduce

To reproduce the issue, train a model using PyTorch-Lightning with mixed precision enabled and the environment described below.

### Expected behavior

Enabling mixed precision should not cause any errors in the metric computation, and the metrics should work correctly.

### Environment

- TorchMetrics version: 1.0.1 (pip)
- Python & PyTorch Version: 3.10 and 2.0.0 (pip)
- OS: Linux (SageMaker)
- Starting container: 763104351884.dkr.ecr.eu-central-1.amazonaws.com/pytorch-training:2.0.0-gpu-py310-cu118-ubuntu20.04-sagemaker

**Comment by SkafteNicki** [comment] 2023-07-28 10:19
Hi @mnslarcher, thanks for reporting this issue.
Would it be possible for you to give some code that reproduces the error.
From the traceback I can see that you call `MulticlassConfusionMatrix` and when I manually try to input different values to the metric (half precision) I cannot reproduce the error.

**Comment by mnslarcher** [comment] 2023-07-28 10:36
> Hi @mnslarcher, thanks for reporting this issue. Would it be possible for you to give some code that reproduces the error. From the traceback I can see that you call `MulticlassConfusionMatrix` and when I manually try to input different values to the metric (half precision) I cannot reproduce the error.

Unfortunately, I have limited coding time, but if I manage it, I'll try to build a minimum example. I cannot share the original code. I'm not using `MulticlassConfusionMatrix` directly; instead, I'm using:

```
JaccardIndex(
    task="binary",
    num_classes=1,
    threshold=0.5,
)
JaccardIndex(
    task="multiclass",
    num_classes=2,
    average="none",
    threshold=0.5,
)
```

I'll definitely keep you posted once I have more information. In the meantime, if anyone has any ideas or insights, I'm open to hearing them and appreciate any input!

**Comment by SkafteNicki** [comment] 2023-07-28 10:45
Alright, thanks for the feedback. The information I am really looking for is: At some point you either call:
```python
metric(preds, target)
```
or 
```python
metric.update(preds, target)
```
if you could provide the output of these two lines:
```python
print(preds.device, preds.dtype, preds.shape, preds.min(), preds.max())
print(target.device, target.dtype, target.shape, target.min(), target.max())
```
it should give me a fairly good idea what is causing this, without you having to share too much information.

**Comment by mnslarcher** [comment] 2023-07-28 14:46
> Alright, thanks for the feedback. The information I am really looking for is: At some point you either call:
> 
> ```python
> metric(preds, target)
> ```
> 
> or
> 
> ```python
> metric.update(preds, target)
> ```
> 
> if you could provide the output of these two lines:
> 
> ```python
> print(preds.device, preds.dtype, preds.shape, preds.min(), preds.max())
> print(target.device, target.dtype, target.shape, target.min(), target.max())
> ```
> 
> it should give me a fairly good idea what is causing this, without you having to share too much information.

Absolutely, I will, it was an experiment I wanted to do, I will post the result here next week when I'll return on the code

**Comment by mnslarcher** [comment] 2023-08-02 14:51
I run the test, I think here the problem is related to PyTorch Lightning not Torch Metrics Because I get:

**Preds**
```
device: cuda:0
dtype: torch.float16
shape: torch.Size([8, 512, 512])
min: tensor(nan, device='cuda:0', dtype=torch.float16)
max: tensor(nan, device='cuda:0', dtype=torch.float16)
```

**Target**
```
device: cuda:0 torch.int64
dtype: torch.int64
shape: torch.Size([8, 512, 512])
min: tensor(0, device='cuda:0')
max: tensor(1, device='cuda:0')
```

@SkafteNicki , Should I open an issue with PyTorch Lightning to see if they have any ideas as to why this happens when I enable mixed precision or do you have any suggestions already? Thanks!

I found this but I don't know if it's relevant:
https://discuss.pytorch.org/t/convolutionbackward0-returned-nan-values-in-its-0th-output/175571/10

I'm using DeepLabV3+ from https://github.com/qubvel/segmentation_models.pytorch with timm-efficientnet-b3 backbone, I don't know, maybe  one of the two is problematic for some module when PL try to use mixed precision.

**Comment by SkafteNicki** [comment] 2023-08-07 07:49
Hi @mnslarcher, sorry for not getting back to you before now.
Yes, then it is definitely a problem somewhere else in the code and has nothing to do with torchmetrics. I would suspect that for some reason your loss becomes `nan` when evaluating in half precision. I would investigate:
1. Does this happen in the very first iteration or in a later? If it happens in the first it probably has to do with the network, else it is the training dynamics (most likely).
2. Is my loss Nan. If so that means that my gradients become nan which means that my network in the following iteration will produce Nan.

I will close this issue, but feel free to open again on Pytorch Lightnings side.

**Closed by SkafteNicki** 2023-08-07 07:49 UTC
Labels: bug / fix, help wanted

**Comment by mnslarcher-enel** [comment] 2023-08-07 07:54
Thanks @SkafteNicki :)! I found something like target=target.long() in the code, I wouldn't want that to be the problem, any idea if in mixed precision you can't have the target as long?

Thanks, I will continue on the PL side if I don't find a solution myself.
