### ISSUE TITLE
Inplace Error When Using MultiClassAccuracy

### ISSUE THREAD

**Issue by haritsahm** [Lightning-AI/torchmetrics#1993] opened 2023-08-11 12:16 UTC
## 🐛 Bug

Inplace update on metrics error when using `MulticlassAccuracy` when computing final validation metrics
### To Reproduce

# register the evaluation metrics as callback
```
log_reid_accuracy:
  _target_: src.callbacks.wandb_metric_callbacks.Accuracy
  metric:
    _target_: torchmetrics.classification.MulticlassAccuracy
    num_classes: 1751
  taskname: reid
```

# callback function
```
class Accuracy(Callback):
    def __init__(self, metric: MulticlassAccuracy, taskname: str = ""):
        #self.num_classes = num_classes
        #self.acc_metrics = {
        #    "age_estimation": MulticlassAccuracy(
        #        num_classes=num_classes,
        #        average="macro",
        #    )
        #}
        self.acc_metric = metric
        self.taskname = taskname
        self.ready = True

    def on_sanity_check_start(
        self, trainer: pl.Trainer, pl_module: pl.LightningModule
    ):
        self.ready = False

    def on_sanity_check_end(
        self, trainer: pl.Trainer, pl_module: pl.LightningModule
    ):
        self.ready = True

    def on_validation_batch_end(
        self,
        trainer: pl.Trainer,
        pl_module: pl.LightningModule,
        outputs: Dict[str, Any],
        batch: Tuple[torch.Tensor, List[Meta]],
        batch_idx: int,
    ):
        taskname = outputs["taskname"]
        if not self.ready or taskname != self.taskname:
            return
        x, metas = batch
        if taskname == "age_estotimation":
            age_types = []
            for meta in metas:
                age_types.append(meta.age_type_id)
            age_types = torch.tensor(age_types,dtype=torch.int32,device=pl_module.device)
            preds = outputs["preds"]
            self.acc_metric.to(pl_module.device)
            self.acc_metric.update(preds.to(pl_module.device),age_types)
        elif taskname == "reid":
            pids = []
            for meta in metas:
                pids.append(meta.person_id)
            pids = torch.tensor(pids,dtype=torch.int32,device=pl_module.device)
            preds = outputs["pid_preds"]
            self.acc_metric.to(pl_module.device)
            self.acc_metric.update(preds.to(pl_module.device),pids)
            
    
    def on_validation_epoch_end(
        self, trainer: pl.Trainer, pl_module: pl.LightningModule
    ):
        if not self.ready:
            return
        self.acc_metric.to(pl_module.device)
        results = self.acc_metric.compute()
        pl_module.log(f"accuracy {self.taskname}", results, on_epoch=True)


```

**pytorch lightning module**
```
def validation_step(self, batch, batch_idx):
  # multitask head
  output_dict = self.model.forward(x, taskname)
  feats = output_dict[taskname]
  _, preds = torch.max(feats, dim=1)

  # compute loss
  ....

  return {
      "loss": losses["total_loss"],
      "features": feats.detach().cpu().clone(), # tested w/o clone()
      "preds": preds.detach().cpu().clone(), # tested w/o clone()
      "taskname": taskname,
  }

```

### Environment

- TorchMetrics version: 0.11.4
- Python & PyTorch Version (e.g., 1.0): 2.1.0a0+fe05266
- Lightning: 2.0.6

### Additional context

```
  File "/home/ubuntu/training/src/callbacks/wandb_metric_callbacks.py", line 637, in on_validation_batch_end
    self.acc_metric.update(preds.to(pl_module.device),age_types)
  File "/usr/local/lib/python3.8/dist-packages/torchmetrics/metric.py", line 400, in wrapped_func
    raise err
  File "/usr/local/lib/python3.8/dist-packages/torchmetrics/metric.py", line 390, in wrapped_func
    update(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchmetrics/classification/stat_scores.py", line 322, in update
    self._update_state(tp, fp, tn, fn)
  File "/usr/local/lib/python3.8/dist-packages/torchmetrics/classification/stat_scores.py", line 70, in _update_state
    self.tp += tp
RuntimeError: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.
```

**Comment by SkafteNicki** [comment] 2023-08-16 12:53
Hi @haritsahm, thanks for reporting this issue.
The error is pretty simple to reproduce:
```python
import torch
import torchmetrics as tm

with torch.inference_mode():
    metric = tm.classification.MulticlassAccuracy(num_classes=3)
metric.update(torch.randint(3, (10,)), torch.randint(3, (10,)))
```
meaning that the metric is initialized in inference mode but called without it. However, it seems very strange to me that this should happen in lightning, because it should only be running inference mode after initialization.
How are the callback initialized in your script?

**Comment by haritsahm** [comment] 2023-08-16 14:04
@SkafteNicki Yes that's right

**Comment by SkafteNicki** [comment] 2023-08-16 18:25
@haritsahm thanks for confirming.
I tried to see if I could locally reproduce the error, but I am unable to do so. Maybe its an error on my side. Some further questions:
* You do not call `torch.inference_mode` anywhere in your code?
* Could you try printing 
  ```python
  for cb in callbacks:
      if isinstance(cb, Accuracy)
          try:
              v = cb.acc_metric.tp._version
              print("Normal tensor")
          except:
              print("Inference tensor")
    ```
    after initializing the callbacks but before `trainer.fit`? This should hopefully clarify if the metric states are already inference tensors before training begins.
* Can you share you codebase? If not, maybe a fully reproducible example? (I know you already shared a lot but I cannot reproduce currently locally)

**Comment by haritsahm** [comment] 2023-08-18 14:03
@SkafteNicki 

- I don't use `torch.inference_mode` anywhere in my code
- The checks return `Inference tensor` before `trainer.fit`
- Unfortunately I can't share the codebase

**Comment by haritsahm** [comment] 2023-08-18 15:05
@SkafteNicki I fixed the issue by adding `with torch.inference_mode():`

So the final code:

```
    def on_validation_batch_end(
        self,
        trainer: pl.Trainer,
        pl_module: pl.LightningModule,
        outputs: Dict[str, Any],
        batch: Tuple[torch.Tensor, List[Meta]],
        batch_idx: int,
    ):
        taskname = outputs["taskname"]
        if not self.ready or taskname != self.taskname:
            return
        x, metas = batch
        with torch.inference_mode(): # Add Inference Mode here
            if taskname == "age_estimation":
                age_types = []
                for meta in metas:
                    age_types.append(meta.age_type_id)
                age_types = torch.tensor(age_types,dtype=torch.int32,device=pl_module.device)
                preds = outputs["preds"]
                self.acc_metric.to(pl_module.device)
                self.acc_metric.update(preds.to(pl_module.device),age_types)
            elif taskname == "reid":
                pids = []
                for meta in metas:
                    pids.append(meta.person_id)
                pids = torch.tensor(pids,dtype=torch.int32,device=pl_module.device)
                preds = outputs["pid_preds"]
                self.acc_metric.to(pl_module.device)
                self.acc_metric.update(preds.to(pl_module.device),pids)
```

**Comment by SkafteNicki** [comment] 2023-08-20 12:36
@haritsahm thanks for you update. 
Sounds like you found a solution. I would also say that you should be able to wrap the full method in `torch.inference_mode`
```python
@torch.inference_mode()
def on_validation_batch_end(
    ...
)
```
I am going to close this issue as it seems to be unrelated to torchmetrics and lightning. It is simply just related to tensors initialized in inference mode cannot be updated inplace. It is still unclear to me why the your callback gets initialized in inference mode (maybe hydra is doing something?) but I guess that you found a solution that works for now.

**Closed by SkafteNicki** 2023-08-20 12:36 UTC
Labels: bug / fix, help wanted
