### ISSUE TITLE
libtorch error from torchmetrics while using Lit-GPT

### ISSUE THREAD

**Issue by aniketmaurya** [Lightning-AI/torchmetrics#1932] opened 2023-07-24 11:31 UTC
## 🐛 Bug

I get the following error on Google Colab while trying [Lit-GPT](https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/download_llama_2.md). If I uninstall `torchaudio` then it works.

```
Traceback (most recent call last):
  File "/content/lit-gpt/scripts/convert_hf_checkpoint.py", line 15, in <module>
    from lit_gpt import Config
  File "/content/lit-gpt/lit_gpt/__init__.py", line 1, in <module>
    from lit_gpt.model import GPT
  File "/content/lit-gpt/lit_gpt/model.py", line 14, in <module>
    from lit_gpt.config import Config
  File "/content/lit-gpt/lit_gpt/config.py", line 8, in <module>
    from lit_gpt.utils import find_multiple
  File "/content/lit-gpt/lit_gpt/utils.py", line 15, in <module>
    from lightning.fabric.loggers import CSVLogger
  File "/usr/local/lib/python3.10/dist-packages/lightning/__init__.py", line 28, in <module>
    from lightning.pytorch.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/__init__.py", line 26, in <module>
    from lightning.pytorch.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/callbacks/__init__.py", line 14, in <module>
    from lightning.pytorch.callbacks.batch_size_finder import BatchSizeFinder
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/callbacks/batch_size_finder.py", line 24, in <module>
    from lightning.pytorch.callbacks.callback import Callback
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/callbacks/callback.py", line 22, in <module>
    from lightning.pytorch.utilities.types import STEP_OUTPUT
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/utilities/types.py", line 25, in <module>
    from torchmetrics import Metric
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/audio/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/audio/pit.py", line 23, in <module>
    from torchmetrics.utilities import rank_zero_warn
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/__init__.py", line 14, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/checks.py", line 25, in <module>
    from torchmetrics.metric import Metric
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/metric.py", line 30, in <module>
    from torchmetrics.utilities.data import (
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/data.py", line 22, in <module>
    from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _XLA_AVAILABLE
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/imports.py", line 48, in <module>
    _TORCHAUDIO_GREATER_EQUAL_0_10: Optional[bool] = compare_version("torchaudio", operator.ge, "0.10.0")
  File "/usr/local/lib/python3.10/dist-packages/lightning_utilities/core/imports.py", line 73, in compare_version
    pkg = importlib.import_module(package)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/torchaudio/_extension/__init__.py", line 43, in <module>
    _load_lib("libtorchaudio")
  File "/usr/local/lib/python3.10/dist-packages/torchaudio/_extension/utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 841, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.10/dist-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZN2at4_ops6conv1d4callERKNS_6TensorES4_RKN3c108optionalIS2_EENS5_8ArrayRefIlEESB_SB_l
```

### To Reproduce

Run this [notebook](https://gist.github.com/aniketmaurya/5d4a243340f87ef2ea85586b732f1adc)

### Expected behavior

Run without any error.

### Environment

```
!pip install --index-url https://download.pytorch.org/whl/nightly/cu118 --pre 'torch>=2.1.0dev' -q
!git clone https://github.com/Lightning-AI/lit-gpt.git
!pip install -r requirements.txt -q
!pip install huggingface_hub sentencepiece -q
```

**Comment by SkafteNicki** [comment] 2023-07-25 09:21
@aniketmaurya this seems to be a problem with nightly release of torchaudio.
Replacing everything in the notebook with just: 
```
!pip install --index-url https://download.pytorch.org/whl/nightly/cu118 --pre 'torch>=2.1.0dev'
import torchaudio
```
reproduces the error. 
I advise reopening the issue on `torchaudio` github.

**Comment by aniketmaurya** [comment] 2023-07-25 09:23
Thank you @SkafteNicki, I'll post this on Torchaudio repo

**Comment by SkafteNicki** [comment] 2023-07-25 09:46
Cool, closing this issue. Feel free to open if issue persist after it v2.1 has been officially released.

**Closed by SkafteNicki** 2023-07-25 09:46 UTC
Labels: bug / fix, help wanted
