### ISSUE TITLE
RuntimeError (Invalid Scalar Type) when training using `bf16-mixed` precision and DDP (gloo backend)

### ISSUE THREAD

**Issue by vincentFrancais** [Lightning-AI/torchmetrics#1809] opened 2023-05-24 13:47 UTC
## 🐛 Bug

When training with `bf16-mixed` precision and DDP (on Windows, using the `gloo` backend), torchmetrics crash with `RuntimeError: Invalid scalar type`. 
Works fine when using single-GPU (no DDP) or `16-mixed` precision.

### To Reproduce

Train a model with a `TorchMetrics` metric with multi-GPU DDP (using the `gloo` backend, not tested using `nccl` backend)  and `bf16-mixed` precision.
Only tested with `AUROC` metric.

<details>
  <summary>Full stack trace</summary>

```
Traceback (most recent call last):
  File "E:\vfrancais\sources\python\pylayermonitoring\debug_metrics.py", line 90, in <module> 
    train(ddp=True, precision="bf16-mixed")
  File "E:\vfrancais\sources\python\pylayermonitoring\debug_metrics.py", line 86, in train
    trainer.fit(model, train_dataloaders=dl, val_dataloaders=val_dl)
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\call.py", line 42, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\strategies\launchers\subprocess_script.py", line 92, in launch
    return function(*args, **kwargs)
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 935, in _run
    results = self._run_stage()
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 976, in _run_stage
Traceback (most recent call last):
    self._run_sanity_check()
  File "E:\vfrancais\sources\python\pylayermonitoring\debug_metrics.py", line 90, in <module>
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1005, in _run_sanity_check 
    train(ddp=True, precision="bf16-mixed")
    val_loop.run()
  File "E:\vfrancais\sources\python\pylayermonitoring\debug_metrics.py", line 86, in train
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\loops\utilities.py", line 177, in _decorator
    trainer.fit(model, train_dataloaders=dl, val_dataloaders=val_dl)
    return loop_run(self, *args, **kwargs)
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\loops\evaluation_loop.py", line 122, in run
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 520, in fit
    return self.on_run_end()
    call._call_and_handle_interrupt(
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\loops\evaluation_loop.py", line 244, in on_run_end
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\call.py", line 42, in _call_and_handle_interrupt
    self._on_evaluation_epoch_end()
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs) 
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\loops\evaluation_loop.py", line 328, in _on_evaluation_epoch_end
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\strategies\launchers\subprocess_script.py", line 92, in launch
    trainer._logger_connector.on_epoch_end()
    return function(*args, **kwargs)
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\connectors\logger_connector\logger_connector.py", line 188, in on_epoch_end
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 559, in _fit_impl
    metrics = self.metrics
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\connectors\logger_connector\logger_connector.py", line 229, in metrics
    self._run(model, ckpt_path=ckpt_path)
    return self.trainer._results.metrics(on_step)
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 935, in _run
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\connectors\logger_connector\result.py", line 474, in metrics
    results = self._run_stage()
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 976, in _run_stage 
    value = self._get_cache(result_metric, on_step)
    self._run_sanity_check()
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\connectors\logger_connector\result.py", line 438, in _get_cache
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1005, in _run_sanity_check
    result_metric.compute()
    val_loop.run()
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\connectors\logger_connector\result.py", line 278, in wrapped_func
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\loops\utilities.py", line 177, in _decorator
    self._computed = compute(*args, **kwargs)
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\connectors\logger_connector\result.py", line 247, in compute
    return loop_run(self, *args, **kwargs)
    return self.value.compute()
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\loops\evaluation_loop.py", line 122, in run
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torchmetrics\metric.py", line 527, in wrapped_func
    return self.on_run_end()
    with self.sync_context( 
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\loops\evaluation_loop.py", line 244, in on_run_end
  File "C:\Users\vfrancais\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 119, in __enter__
    self._on_evaluation_epoch_end()
    return next(self.gen)
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\loops\evaluation_loop.py", line 328, in _on_evaluation_epoch_end
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torchmetrics\metric.py", line 498, in sync_context
    trainer._logger_connector.on_epoch_end()
    self.sync(
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\connectors\logger_connector\logger_connector.py", line 188, in on_epoch_end
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torchmetrics\metric.py", line 450, in sync
    metrics = self.metrics
    self._sync_dist(dist_sync_fn, process_group=process_group)
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\connectors\logger_connector\logger_connector.py", line 229, in metrics
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torchmetrics\metric.py", line 359, in _sync_dist
    return self.trainer._results.metrics(on_step)
    output_dict = apply_to_collection(
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\connectors\logger_connector\result.py", line 474, in metrics
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torchmetrics\utilities\data.py", line 186, in apply_to_collection
    value = self._get_cache(result_metric, on_step)
    return elem_type({k: apply_to_collection(v, dtype, function, *args, **kwargs) for k, v in data.items()})
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\connectors\logger_connector\result.py", line 438, in _get_cache
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torchmetrics\utilities\data.py", line 186, in <dictcomp>
    result_metric.compute()
    return elem_type({k: apply_to_collection(v, dtype, function, *args, **kwargs) for k, v in data.items()})
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\connectors\logger_connector\result.py", line 278, in wrapped_func
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torchmetrics\utilities\data.py", line 192, in apply_to_collection
    self._computed = compute(*args, **kwargs)
    return elem_type([apply_to_collection(d, dtype, function, *args, **kwargs) for d in data])
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\lightning\pytorch\trainer\connectors\logger_connector\result.py", line 247, in compute
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torchmetrics\utilities\data.py", line 192, in <listcomp>
    return self.value.compute()
    return elem_type([apply_to_collection(d, dtype, function, *args, **kwargs) for d in data])
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torchmetrics\metric.py", line 527, in wrapped_func
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torchmetrics\utilities\data.py", line 182, in apply_to_collection
    with self.sync_context(
    return function(data, *args, **kwargs)
  File "C:\Users\vfrancais\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 119, in __enter__
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torchmetrics\utilities\distributed.py", line 137, in gather_all_tensors
    return next(self.gen)
    return _simple_gather_all_tensors(result, group, world_size)
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torchmetrics\metric.py", line 498, in sync_context
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torchmetrics\utilities\distributed.py", line 98, in _simple_gather_all_tensors
    self.sync(
    torch.distributed.all_gather(gathered_result, result, group)
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torchmetrics\metric.py", line 450, in sync
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 1436, in wrapper
    self._sync_dist(dist_sync_fn, process_group=process_group)
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torchmetrics\metric.py", line 359, in _sync_dist
    return func(*args, **kwargs)
    output_dict = apply_to_collection(
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 2440, in all_gather
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torchmetrics\utilities\data.py", line 186, in apply_to_collection
    return elem_type({k: apply_to_collection(v, dtype, function, *args, **kwargs) for k, v in data.items()})
    work.wait()
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torchmetrics\utilities\data.py", line 186, in <dictcomp>
RuntimeError: Invalid scalar type
    return elem_type({k: apply_to_collection(v, dtype, function, *args, **kwargs) for k, v in data.items()})
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torchmetrics\utilities\data.py", line 192, in apply_to_collection
    return elem_type([apply_to_collection(d, dtype, function, *args, **kwargs) for d in data])
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torchmetrics\utilities\data.py", line 192, in <listcomp>
    return elem_type([apply_to_collection(d, dtype, function, *args, **kwargs) for d in data])
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torchmetrics\utilities\data.py", line 182, in apply_to_collection
    return function(data, *args, **kwargs)
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torchmetrics\utilities\distributed.py", line 137, in gather_all_tensors
    return _simple_gather_all_tensors(result, group, world_size)
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torchmetrics\utilities\distributed.py", line 98, in _simple_gather_all_tensors
    torch.distributed.all_gather(gathered_result, result, group)
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 1436, in wrapper
    return func(*args, **kwargs)
  File "E:\vfrancais\sources\python\pylayermonitoring\.venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 2440, in all_gather
    work.wait()
RuntimeError: Invalid scalar type
```
</details>

<details>
  <summary>Code sample</summary>

```python
from typing import Any, Optional, Literal

import lightning as pl
import torch
import torchmetrics
from lightning.pytorch.strategies import DDPStrategy
from lightning.pytorch.utilities.types import STEP_OUTPUT
from torch.utils.data import Dataset, DataLoader


class RandomDataset(Dataset):
    def __init__(self, num_samples):
        self.len = num_samples
        self.data = torch.rand(num_samples)
        self.targets = torch.randint(0, 1, (num_samples,))

    def __getitem__(self, index):
        return self.data[index], self.targets[index]

    def __len__(self):
        return self.len


class BoringModel(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 1)
        self.auroc = torchmetrics.classification.BinaryAUROC(pos_label=1)

    def forward(self, x):
        return self.layer(x)

    def loss(self, batch, prediction):
        # An arbitrary loss to have a loss that updates the model weights during `Trainer.fit` calls
        return torch.nn.functional.mse_loss(prediction, torch.ones_like(prediction))

    def training_step(self, batch, batch_idx):
        data, targets = batch
        logit = self.layer(data)
        loss = self.loss(targets, logit)
        return {"loss": loss}

    def on_train_batch_end(self, outputs: STEP_OUTPUT, batch: Any, batch_idx: int) -> None:
        loss = outputs['loss']
        self.log("train/loss", loss, prog_bar=True)

    def on_train_epoch_end(self) -> None:
        pass

    def validation_step(self, batch, batch_idx):
        data, targets = batch
        logits = self.layer(data)
        loss = self.loss(targets, logits)
        return {"loss": loss, "logits": logits, "targets": targets}

    def on_validation_batch_end(
            self, outputs: Optional[STEP_OUTPUT], batch: Any, batch_idx: int, dataloader_idx: int = 0
    ) -> None:
        loss = outputs['loss']
        logits = outputs['logits']
        targets = outputs['targets']
        self.auroc(logits.sigmoid().squeeze(), targets.int())
        self.log("val/auroc", self.auroc, prog_bar=True)
        self.log("val/loss", loss, prog_bar=True, sync_dist=True)

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
        lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1)
        return [optimizer], [lr_scheduler]


def train(ddp: bool, precision: Literal["16-mixed", "bf16-mixed"]):
    dataset = RandomDataset(1000)
    dataset_val = RandomDataset(500)
    dl = DataLoader(dataset, batch_size=32, pin_memory=True, num_workers=1, drop_last=True)
    val_dl = DataLoader(dataset_val, batch_size=32, pin_memory=True, num_workers=1, drop_last=True)
    model = BoringModel()
    strategy = DDPStrategy(process_group_backend='gloo') if ddp else 'auto'
    devices = -1 if ddp else 1
    trainer = pl.Trainer(max_epochs=3, accelerator="gpu", devices=devices,
                         strategy=strategy, precision=precision
                         )
    trainer.fit(model, train_dataloaders=dl, val_dataloaders=val_dl)


if __name__ == "__main__":
    train(ddp=True, precision="16-mixed")       # Do not crash
    # train(ddp=True, precision="bf16-mixed")   # Crash
    # train(ddp=False, precision="bf16-mixed")  # Do not crash
    # train(ddp=False, precision="16-mixed")    # Do not crash

```

</details>

### Expected behavior

No crash should happen if using `bf16-mixed` precision with DDP.

### Environment

- pytorch-lightning: 2.0.0  (pip)
- pytorch: 2.0.0+cu117      (pip)
- torchmetrics: 0.11.4        (pip)
- Python 3.9.16 [MSC v.1929 64 bit (AMD64)] 
- Windows Server 2019, version 1809
- GPUs: RTX A5000 x2, CUDA version 11.7.64

**Comment by SkafteNicki** [comment] 2023-05-26 12:04
Hi @vincentFrancais, thanks for reporting this issue.
I can indeed reproduce the error. That said when I try with the `nccl` backend everything works as expected, so I think the issue is with the `gloo` backend. The traceback indicates that the problem is with when we synchronize between processes:
```python
    torch.distributed.all_gather(gathered_result, result, group)
``` 
therefore, I highly suspect that the error is not related to TM but instead that there is not support for `bfloat16` in pytorch, when using the `gloo` backend.

**Comment by SkafteNicki** [comment] 2023-06-02 06:05
Yeah, I definitely think that it is due to some unsupported dtypes for that particular backend, which is not much we can do about, this is a issue on Pytorch side or gloo to be more precise.
Closing issue.

**Closed by SkafteNicki** 2023-06-02 06:05 UTC
Labels: bug / fix, help wanted
